name: Export

on:
  workflow_dispatch:
    inputs:
      publish-release:
        description: 'Publish Release'
        type: boolean
        default: false
      publish-pre-release:
        description: 'Mark as Pre-Release'
        type: boolean
        default: false
      version-number:
        description: 'Version Number for Release'
        type: string

jobs:
  export:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-22.04
    
    permissions:
      contents: write

    steps:
      - name: Checkout latest
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.godotengine.org/?version=4.5&flavor=stable&slug=mono_linux_x86_64.zip&platform=linux.64
          godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.5&flavor=stable&slug=mono_export_templates.tpz&platform=templates
          cache: true
          archive_output: ${{ github.event.inputs.publish-release }}
          relative_project_path: ./
          
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Windows"
          path: ${{ steps.export.outputs.build_directory }}/Windows/*

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Linux"
          path: ${{ steps.export.outputs.build_directory }}/Linux/*
          
      - name: Publish release
        if: ${{ github.event.inputs.publish-release == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
              ${{ steps.export.outputs.archive_directory }}/Windows.zip
              ${{ steps.export.outputs.archive_directory }}/Linux.zip
          tag_name: ${{ github.event.inputs.version-number }}
          prerelease: ${{ github.event.inputs.publish-pre-release }}